name: Create Release on Demand

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: echo "RELEASE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Build Plasmo addon
        run: npm run package # Assuming this command creates the zip files in the 'dist' folder

      - name: Create a new GitHub release
        id: create_release
        run: |
          # Use the version from package.json to create the release tag
          TAG_NAME="v${{ env.RELEASE_VERSION }}"
          gh release create $TAG_NAME ./dist/*.zip --title "Release $TAG_NAME" --notes "Release created by GitHub Actions"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token for authentication

      - name: Upload release assets
        run: |
          # Upload all zip files in the dist folder
          for file in ./dist/*.zip; do
            gh release upload $TAG_NAME $file --clobber
          done
