name: Create Release on Demand

on:
  workflow_dispatch:

permissions:
  contents: write # Allow creating and updating releases
  id-token: write # Allow creating a release tag
  pull-requests: read # Allow reading pull requests if needed (optional)

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: echo "RELEASE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Build Plasmo addon
        run: npm run package

      - name: Create a new GitHub release
        id: create_release
        run: |
          # Use the version from package.json to create the release tag
          TAG_NAME="v${{ env.RELEASE_VERSION }}"
          gh release create $TAG_NAME ./build/*.zip --title "Release $TAG_NAME" --notes "Release created by GitHub Actions"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        run: |
          # Upload all zip files in the dist folder
          TAG_NAME="v${{ env.RELEASE_VERSION }}"
          for file in ./build/*.zip; do
            gh release upload $TAG_NAME "$file" --clobber
          done
